Improve fullPathRE regex
blokhinnv/wikidataqidlabels pull request #2
Opened 2020-11-19 16:37 UTC by AtilioA

So it will also capture this URI format: http://www.wikidata.org/entity/Q1.

I get this format from my SPARQL queries. This URI is also cited here: https://www.wikidata.org/wiki/Wikidata:Glossary#Entity

![image](https://user-images.githubusercontent.com/27153776/99695429-51138380-2a6c-11eb-8e85-a9ef71718214.png)

2020-11-19 20:19 UTC, blokhinnv requested changes
Actually, I think we should just delete the `fullPathRE` part instead of modifying it. 

Although you are absolutely correct, there could be different URIs for the entity, it doesn't matter because of the current implementation. I used `vscode.TextDocument.getWordRangeAtPosition` method to get the word under the cursor (which should be QID for the hover to show up), so the full URI will never be selected and `fullPathRE.test(word)` is always `false`.

2020-11-19 23:28 UTC, AtilioA commented
I don't think I follow. For the URIs, the selection under the cursor is the full URI (not the QID). For example, The current version has this problem:
![2020-11-19_20-12](https://user-images.githubusercontent.com/27153776/99736069-81771400-2aa4-11eb-8ae1-8010de40f30d.png)
![2020-11-19_20-12_1](https://user-images.githubusercontent.com/27153776/99736072-820faa80-2aa4-11eb-9259-9105699d6755.png)

(Regex with PR)
![2020-11-19_20-24](https://user-images.githubusercontent.com/27153776/99736525-4c1ef600-2aa5-11eb-8fdc-a5a8876dbb4b.png)
![2020-11-19_20-24_1](https://user-images.githubusercontent.com/27153776/99736530-4cb78c80-2aa5-11eb-93f2-e629cda864ac.png)


I also noticed that `qid.replace` should be changed as well, so I did that. I made `fullPathRE` a global constant if that's ok. Better than having it declared twice in separate places.

2020-11-20 14:56 UTC, blokhinnv approved these changes
I checked it again to understand why it works in a different way for me. 

It looks like this happens because you use JSON format, and I tested it only with plain text and csv. Indeed, if I set language mode as JSON (no matter if the file is actually JSON), the selection under the cursor becomes the full URI. I had no idea that language mode affects the behaviour of `getWordRangeAtPosition`. By the way, if you could confirm that it works the same way for you, it would be nice.

2020-11-20 14:58 UTC, merged

2020-11-20 15:13 UTC, AtilioA commented
> It looks like this happens because you use JSON format, and I tested it only with plain text and csv.

Indeed. Testing plain text and csv, the regex or whatever fails for some reason, unless I place the cursor directly above the QID. For JSON files that wouldn't happen but it is fixed now 👍 .